
[Main]
	#List of items to won xp with mining ex : "modid:blockid:xpearn:minlevel:maxlevel:{JsonFormat}; etc..." put 0 for maxlevel to disable limit, for JsonFormat see wiki
	"Mining earning" = "modid:blockid:120:0:0:{}"
	#List of items to won xp with mining ex : "modid:blockid:xpearn:minlevel:maxlevel:{JsonFormat}; etc..." put 0 for maxlevel to disable limit, for JsonFormat see wiki
	"Crafting earning" = "modid:blockid:120:0:0:{}"
	#List of items to won xp with mining ex : "modid:blockid:xpearn:minlevel:maxlevel:{JsonFormat}; etc..." put 0 for maxlevel to disable limit, for JsonFormat see wiki
	"Smelting Earning" = "modid:blockid:120:0:0:{}"
	#List of items to won xp with mining ex : "modid:blockid:xpearn:minlevel:maxlevel:{JsonFormat}; etc..." put 0 for maxlevel to disable limit, for JsonFormat see wiki
	"Killing Earning" = "modid:blockid:120:0:0:{}"

